2019-12-14 22:49:08,792 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 22:49:13,819 ERROR: Exception on /lzhang3/followers [GET] [in c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\routes.py", line 161, in followers
    followers=followers)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\followers.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\followers.html", line 14, in root
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\base.html", line 14, in root
    <span class="icon-bar"></span>
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\base.html", line 81, in block_content
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\followers.html", line 30, in block_app_content
  File "C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\templates\_follower.html", line 13, in root
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\lzhan\documents\github\nnhsse-flask\luke-home\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'follower'. Did you mean 'followers' instead?
2019-12-14 23:00:38,284 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:03:51,885 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:04:39,960 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:06:24,150 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:06:53,926 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:07:59,027 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:10:18,955 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:14:56,872 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:15:42,838 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:17:20,594 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:17:27,001 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:23:40,794 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:28:40,117 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
2019-12-14 23:29:25,613 INFO: Microblog startup [in C:\Users\lzhan\Documents\GitHub\nnhsse-flask\luke-home\microblog\app\__init__.py:45]
